defaults:
  - dataset: nmr
  - optional dataset/view_sampler_dataset_specific_config: ${dataset/view_sampler}_${dataset}
  - model/encoder: epipolar
  - model/decoder: splatting_cuda
  - loss: [mse]

output_dir: null

wandb:
  project: freesplat
  entity: placeholder
  name: placeholder
  mode: offline

mode: train

dataset:
  overfit_to_scene: null

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 16
    persistent_workers: true
    batch_size: 1
    seed: 1234
  test:
    num_workers: 4
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 1
    persistent_workers: true
    batch_size: 1
    seed: 3456

optimizer:
  lr: 1.e-4
  warm_up_steps: 100
  cosine_lr: true

checkpointing:
  load: null
  every_n_train_steps: 10000
  save_top_k: 5
  monitor: val_psnr_probabilistic
  mode: max
  save_last: true
  filename: best_step_{step:06d}_{val_psnr_probabilistic:.4f}

train:
  load_depth: null
  depth_mode: null
  extended_visualization: false
  train_only_importance_head: true #仅训练 Importance Head 开关配置项
  importance_head_lr: 1.e-4
  to_gaussians_lr: 1.e-5
  depth_decoder_lr: 1.e-5
  high_resolution_skip0_lr: 1.e-5

test:
  output_path: outputs/test
  visualize_voxel: false #测试时可视化开关配置项
  measure_decoder_peak_memory: true #测试阶段测量解码器峰值内存开关配置项

seed: 111123

strict: true

trainer:
  max_steps: -1
  val_check_interval: 5000
  gradient_clip_val: 0.01
  prog_bar: True
